apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wXpKdEGVH6EtbJJ9lRCL4Ssb6xVSMMvT4hWgSbJ/6lA+EtX+,iv:n1K39FbSE1FT2sheYNDGrfhk61hEKCWMHHOs/coIpsM=,tag:X6kT7AiYchW47qJD6EMaRA==,type:str]
    credentials.json: ENC[AES256_GCM,data:UTjbhR/b8Bc3L3LjDV+9DTaEpRKiBNtdRXIbCkkQTb6wtulnaWnOOOUJecVq5F7vgCpjARkFcBDcdCL56X1s17AR1Y/uAUWD3LMyuqBnp+e/CuifPvFVFrb1vQLsutlhzIa5iljKrUdUfuIpMBIIgQZlLPTlfj1DUYstKX8b/J8T+O+x2m7vf+LIQbYDC/Xw00UUOPljpG0AVow2PBuneK2qJTRphQSATV5uC4W5Gg==,iv:ltGs2UFlh1sIAnK9oQcxVgmkCHnBJhe2KYRTZXkFogw=,tag:qaDgK3+Ng05OW543jOIiCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu6l38vuhpts52zm7vncjtcr34cg2nqqeyree7qvl59jlfez55asjm64pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUQ3cHhWcDBjbi9CY3cr
            b3k3OGt3SThqeHRibWx6cHR6c0lKSFZkaFJNCjdVR0czd0ozVGVrNVd4L1hCaFlp
            YS81R1NJVVBoZmd2VXpUemd6V05DUXcKLS0tIFJ0emhmZnFyNkxCbGZvbWROclpM
            KzZhK2RMcHZtK2gwMEd1dDU5Zld5NlEKy4TEEO5S75UKaAyR6mNMC8hWhVVriEvM
            tEpqZUHhzaVLFUWbe8tdDRDeWV7CZXjhjDoDYMjMyLsgCk3RYvyKgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T22:47:42Z"
    mac: ENC[AES256_GCM,data:wMZe0tUtzK6hSAX2xAdDb2rDIEJmA3h9pc8aczQGT5JvgnkZFTP3d+Q1ahMX/5JCy4ARGS19BlK0+EhrEc9wOipYBhkh1/yW1aa0PvnAsDIvg/rzUXNzdiV8hkQx3ODCK7kRmoxvv4vhYtQh7zBnudf71nL33WDQY5mlfnis90w=,iv:BV4C9Ku4R71Hn+Psbsy/AmCSuMCVHchp5fcnslNuLf0=,tag:VN670D6XVJsjWs8MRvvFrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
