apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:YiF/qCHnPRfhXbDO+JQdgti7sn+t71uCfUuuQi4gCWE6eDzGnyBrQGgnGYElnIOKskxttmKclHaKYxzpQEms/SmyjXPLZaFMX1X3i+IZEwYoIhHixg6iNlAU5boGtw==,iv:/7dM+z8G5tUewjVta4YGfv2dRfvo1nFWWHpfzpdJfdQ=,tag:XUwmkc80GXY06rZNeKCwAQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:9G1nR1utpQ/g1sTIjQ==,iv:+8L4HjqEX1+Sw18eIKG8bpDnLeWaG/A5vbWrsxk6GaU=,tag:S0ALVIe1RsQ+YOzQz3iRDw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:bghkCvsPeeESu0mosq43Ji7pafCL,iv:CAUtf1xF9Kkn4aEU44cabf6moqM0iuAj06LcQnnHwIY=,tag:bsUSO0Iv42LsDeZVyqsDKw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:WxU1KD+gznM6TvHOuNIMrpZV6WJ1EchaUE6yrWdYNgLkUl9B,iv:A85Sp1TgKIL3tGzTQL+yjcrwhuVHv/HOeuZQ4aIiYyE=,tag:yeFBW5DsGEilyutcMZndFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu6l38vuhpts52zm7vncjtcr34cg2nqqeyree7qvl59jlfez55asjm64pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UW44Vmd0QlRRTnpPNWJE
            Nmx0ME9kV0g5YXlRak83b3ppZ25YT0svbEFnCjQzMXo5NU5PQXh5b1RQWStPTEtw
            OVl5dVE5aGU3cFJaZ1FPWHVWMHFqSDgKLS0tIFBUZW55WW94UTdjZ1kyeTJSQTdn
            dWd5VjJmWk12UlBrSXlBd24xQ2pMZ1kK4jsnbUt6cJi2szKjkYdYZH8gJBmKYWlv
            XZ6wdxF+tkQeFgrDfCqC+ceiZ4Q5K7lQRuae6g2AXTbBF0unygfvDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T22:47:42Z"
    mac: ENC[AES256_GCM,data:SnXgnudwMooAK+Ws/ZNOZO9MoLtwxEwtPdRNYaNgFO6i0DcJ+mZfEpcCAcTtHdIo7dcjeRktqMBrBaNZVoBCEuC97bPUMZjxyp8tMj5RTbor+hTFneEFvq0q+D9a0Trc5yjO0sOofBI5n84BuKS5eEx5a/0a6+nRVaJPPjZDnIU=,iv:pDzxm1uDjI25wsXDyLT2+TVlgxmHxNVTmHNzno3yYiU=,tag:EHuAK+l303bGyM781lT7EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
